### ISSUE TITLE
gh-release is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Prince-Hamza** [ungoldman/gh-release#174]
yarn add gh-release
gh-release
gives error : gh-release is not recognized as an internal or external command

**Comment by jgravois** [comment]
i think something might be up with your local installation of yarn

```
box~ % cd code/test
box~/code/test % yarn add gh-release
yarn add v1.22.17
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Saved lockfile.
warning Your current version of Yarn is out of date. The latest version is "1.22.18", while you're on "1.22.17".
info To upgrade, run the following command:
$ curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
success Saved 183 new dependencies.
info Direct dependencies
└─ gh-release@6.0.4
info All dependencies
├─ @babel/code-frame@7.16.7
├─ @babel/helper-validator-identifier@7.16.7
├─ @babel/highlight@7.17.9
```

**Comment by ungoldman** [comment]
I'm not 100% sure but I don't believe yarn adds binary aliases to the global PATH by default for local installs. If you're trying to install gh-release globally with yarn, I believe the command you're looking for might be `yarn global add gh-release`.

That said, I would recommend avoiding global installs. The recommended workflow is to install install gh-release at the local (package.json) level, then runn it via the package.json `scripts` field, e.g.

```
  "scripts": {
    "release": "gh-release"
  }
```

The way to access the example script above with yarn would then be `yarn run release`.

The advantage of this approach is that the installed version of gh-release is checked into version control via package.json, and the global namespace of your terminal environment is not polluted with another random program.

---

Final Note:

With the command you ran above, you should be able to access gh-release straight from the command line without modifying your default PATH configuration like so:

```
yarn add gh-release
./node_modules/.bin/gh-release
```

(Please note that I don't recommend actually doing this as a common practice)

Hope that helps ✌️
