### ISSUE TITLE
Add support for Github enterprise

### ISSUE THREAD

**Issue by henryhuang** [ungoldman/gh-release#44]
I hope it could support for Gitub enterprise version, because the server endpoint is my corporation's private github server.

**Comment by ungoldman** [comment]
Hi @henryhuang! I'd be happy to support this feature in the future, but I do not have access to an Github Enterprise server myself. If you are interested in supporting that functionality I would encourage you to [contribute](https://github.com/ungoldman/gh-release/blob/master/CONTRIBUTING.md) with a pull request.

**Comment by henryhuang** [comment]
@ungoldman , ok, let me try

**Comment by ungoldman** [comment]
@henryhuang your contribution was released as part of `v2.2.0` (see #46). Thank you!
